server:
  port: 8080
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/carservice
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}

logging:
  level:
    sql: debug

kafka:
  producer.id: 1
  topic:
    request.log: request_logs
    token.grant.log: token_grant_logs
