spring:
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yml
    default-schema: "carservice"
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/carservice"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/carservice"
  jpa:
    open-in-view: false
    properties:
      javax.persistence.validation.mode: none
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate.show_sql: true
      hibernate.connection.characterEncoding: utf8mb4
      hibernate.connection.CharSet: utf8mb4
      hibernate.connection.useUnicode: true
      hibernate:
        ddl-auto: validate

server:
  port: 8080